### ISSUE TITLE
Delay in wheel tfs 

### ISSUE THREAD

**Issue by pmukherj** [husky/husky_viz#2]
Wheel tfs take a while for the joint_publisher (running on the base station) and robot_state_publisher (running on the robot) to communicate and publish properly. There is about a five second delay in the wheel tfs showing up in rviz.

**Comment by jeff-o** [comment]
The real solution is that joint_state_publisher needs to be removed from view_robot.  On more complex robots (like those with arms) the joint_state_publisher conflicts with real joints.
