### ISSUE TITLE
Interactive markers dont work.

### ISSUE THREAD

**Issue by ibaranov-cp** [husky/husky_viz#3]
For some reason, using interactive markers doesn't seem to work anymore.

An image with this issues is here:
https://s3.amazonaws.com/CPR_PUBLIC/LEARN_ROS/Learn_ROS-disk1.vmdk
https://s3.amazonaws.com/CPR_PUBLIC/LEARN_ROS/Learn_ROS.ovf
Login (username): user
Password: learn

Starting 
roslaunch husky_gazebo husky_empty_world.launch
roslaunch husky_viz view_robot.launch

Placing an interactive marker does nothing...

**Comment by mikepurvis** [comment]
The husky_interactive_markers package should die in favour of the robot-agnostic version: https://github.com/husky/husky_base/issues/2

When that's resolved, remove launching the marker server from view_robot.launch here, and close the ticket.
